services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    working_dir: /app
    command: flask --app app.main run --host=0.0.0.0 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  frontend:
    depends_on:
    - backend
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always